--PL/SQL konzolra írjon kimenetet, ha a kód futtatása során hiba történik
   SET SERVEROUTPUT ON;

-- Táblák eldobása (ha léteznek)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE befogasok CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE pokemonok CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE edzok CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE naplo CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

CREATE TABLE edzok (
   edzo_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nev              VARCHAR2(100) NOT NULL,
   regio            VARCHAR2(50),
   tapasztalat_pont NUMBER DEFAULT 0,
   kezdes_eve       NUMBER
);

CREATE TABLE pokemonok (
   pokedex_szam NUMBER PRIMARY KEY,
   nev          VARCHAR2(100) NOT NULL,
   tipus        VARCHAR2(50) NOT NULL,
   alap_hp      NUMBER
);

CREATE TABLE befogasok (
   befogas_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   edzo_id      NUMBER
      REFERENCES edzok ( edzo_id ),
   pokedex_szam NUMBER
      REFERENCES pokemonok ( pokedex_szam ),
   szint        NUMBER(3) CHECK ( szint BETWEEN 1 AND 100 ),
   datum        DATE DEFAULT sysdate
);

CREATE TABLE naplo (
   id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   esemeny_tipus VARCHAR2(50),
   leiras        VARCHAR2(255),
   datum         DATE DEFAULT sysdate,
   felhasznalo   VARCHAR2(50) DEFAULT user
);

-- Mintaadatok
INSERT INTO edzok (
   nev,
   regio,
   tapasztalat_pont,
   kezdes_eve
) VALUES
   ( 'Ash Ketchum',
     'Kanto',
     1500,
     2020 );
INSERT INTO edzok (
   nev,
   regio,
   tapasztalat_pont,
   kezdes_eve
) VALUES
   ( 'Misty',
     'Kanto',
     1200,
     2019 );
INSERT INTO edzok (
   nev,
   regio,
   tapasztalat_pont,
   kezdes_eve
) VALUES
   ( 'Brock',
     'Kanto',
     1300,
     2018 );
INSERT INTO edzok (
   nev,
   regio,
   tapasztalat_pont,
   kezdes_eve
) VALUES
   ( 'Goh',
     'Galar',
     400,
     2024 );

INSERT INTO pokemonok VALUES
   ( 1,
     'Bulbasaur',
     'Fű/Méreg',
     45 );
INSERT INTO pokemonok VALUES
   ( 4,
     'Charmander',
     'Tűz',
     39 );
INSERT INTO pokemonok VALUES
   ( 7,
     'Squirtle',
     'Víz',
     44 );
INSERT INTO pokemonok VALUES
   ( 25,
     'Pikachu',
     'Elektromos',
     35 );
INSERT INTO pokemonok VALUES
   ( 143,
     'Snorlax',
     'Normál',
     160 );

INSERT INTO befogasok (
   edzo_id,
   pokedex_szam,
   szint,
   datum
) VALUES
   ( 1,
     25,
     42,
     sysdate - 100 );
INSERT INTO befogasok (
   edzo_id,
   pokedex_szam,
   szint,
   datum
) VALUES
   ( 1,
     143,
     30,
     sysdate - 50 );
INSERT INTO befogasok (
   edzo_id,
   pokedex_szam,
   szint,
   datum
) VALUES
   ( 2,
     7,
     28,
     sysdate - 200 );
INSERT INTO befogasok (
   edzo_id,
   pokedex_szam,
   szint,
   datum
) VALUES
   ( 3,
     4,
     32,
     sysdate - 150 );
COMMIT;